/** Messages exchanged with the isolated ffmpeg renderer worker. */
export type VideoMediaType = 'photo' | 'video' | 'animated_gif';
export type VideoStitchStyle = 'seamless' | 'gallery';
export type VideoFrame = 'original' | 'top' | 'bottom';

export interface VideoRenderInput {
  blob: Blob;
  type: VideoMediaType;
}

export interface VideoRenderRequest {
  type: 'start';
  id: string;
  inputs: VideoRenderInput[];
  style: VideoStitchStyle;
  background: `#${string}`;
  frame: VideoFrame;
  locale: 'zh-CN' | 'en';
}

export interface VideoRenderLayout {
  type: 'layout';
  id: string;
  /** Dimensions of the media strip before a source frame is added. */
  width: number;
  height: number;
  duration: number;
}

export interface VideoRenderFrame {
  type: 'frame';
  id: string;
  /** An exact-width, even-height PNG generated by the existing frame renderer. */
  blob?: Blob;
  height?: number;
}

export interface VideoRenderProgress {
  type: 'progress';
  id: string;
  phase: 'loading' | 'probing' | 'encoding';
  progress?: number;
}

export interface VideoRenderDone {
  type: 'done';
  id: string;
  blob: Blob;
  width: number;
  height: number;
  duration: number;
}

export interface VideoRenderFailure {
  type: 'error';
  id: string;
  error: string;
}

export type VideoRenderWorkerMessage =
  VideoRenderLayout | VideoRenderProgress | VideoRenderDone | VideoRenderFailure;

export type VideoRenderInboundMessage = VideoRenderRequest | VideoRenderFrame;
